### ISSUE TITLE
Can this only fetch files/images from the web or also files stored locally?

### ISSUE THREAD

**Issue by arshdeepsangha** [avipunes/file-viewer#17]
How can i reference files like pdf, docx stored locally?

**Comment by arshdeepsangha** [comment]
Also all of the documents don't load for me on the 1.2.0 version. PDF and JPEG online files load fine using 1.1.0 version.

**Comment by avipunes** [comment]
> Also all of the documents don't load for me on the 1.2.0 version. The error message i get is "File extension is not supported." on 1.2.0 version. PDF and JPEG online files load fine using 1.1.0 version.

Firstly to expose your local files to the public. You can use packages like [localtunnel](https://theboroer.github.io/localtunnel-www/) or [ngrok](https://ngrok.com).

About supported file, make sure the file extension is 'pdf'

**Comment by arshdeepsangha** [comment]
> > Also all of the documents don't load for me on the 1.2.0 version. The error message i get is "File extension is not supported." on 1.2.0 version. PDF and JPEG online files load fine using 1.1.0 version.
> 
> Firstly to expose your local files to the public. You can use packages like [localtunnel](https://theboroer.github.io/localtunnel-www/) or [ngrok](https://ngrok.com).
> 
> About supported file, make sure the file extension is 'pdf'

What i meant to ask is if i can configure it view blob pdf, docx, jpg or png files?

**Comment by arshdeepsangha** [comment]
@avipunes ?

**Comment by avipunes** [comment]
> @avipunes Do you know how can i view .docx and .xlsx blob files ?

Under the hood, this library uses Microsoft API which needs a public URL. Can yo6 share the URL of the file you're using?

**Comment by arshdeepsangha** [comment]
> > @avipunes Do you know how can i view .docx and .xlsx blob files ?
> 
> Under the hood, this library uses Microsoft API which needs a public URL. Can yo6 share the URL of the file you're using?

This is the url generated by the `createObjectURL` function after passing the uploadedFile into it.
`blob:http://localhost:8080/9cf55be4-a822-4a49-bf56-812ce6f9a87e`

![image](https://user-images.githubusercontent.com/42809859/222955614-8bf34e29-ea0c-4a33-b6d8-693d7d01209e.png)

**Comment by avipunes** [comment]
> > > @avipunes Do you know how can i view .docx and .xlsx blob files ?
> 
> > 
> 
> > Under the hood, this library uses Microsoft API which needs a public URL. Can yo6 share the URL of the file you're using?
> 
> 
> 
> This is the url generated by the `createObjectURL` function after passing the uploadedFile into it.
> 
> `blob:http://localhost:8080/9cf55be4-a822-4a49-bf56-812ce6f9a87e`
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/42809859/222955614-8bf34e29-ea0c-4a33-b6d8-693d7d01209e.png)
> 
> 
> 
> Its not a public URL, its a file url of a file that was uploaded locally. I guess my other option would be a DOCX to HTML converter library that i can use to preview the file with? Or any better suggestions?
> 
> 

As I said, the library supports ONLY URLs publicly open to the internet. Localhost won't work.
