### ISSUE TITLE
GET http://localhost:35729/livereload.js?snipver=1 net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by TumeloM2** [avipunes/file-viewer#2]
Hi there.
I added file-viewer to my React project and I keep getting this error:
GET http://localhost:35729/livereload.js?snipver=1 net::ERR_CONNECTION_REFUSED
I went to the bundle.js file in the file viewer node modules and and I changed 'localhost" to my machine's dns ip address, then to 127.0.0.1, still get the same error.

**Comment by avipunes** [comment]
@TumeloM2 , sense under the hood, this package uses a third party viewer (office 365 excel viewer) for excel type of files.
Therefore the third party can't access your local storage files.
there are some tools for exposing your localhost such as https://ngrok.com/
