### ISSUE TITLE
https://www.office.com/redir.aspx?assetid=HA102724036

### ISSUE THREAD

**Issue by abindadna** [avipunes/file-viewer#3]
I can't load office file. Error message "An error occurred, We're sorry, but for some reason we can't open this for you." 
when I open the link to learn more leads to https://www.office.com/redir.aspx?assetid=HA102724036

**Comment by avipunes** [comment]
@abindadna , what file URL are you passing to the `url ` attribute?

**Comment by abindadna** [comment]
yes, I've found a problem with the url that I use. thank you

**Comment by Wajidmlk** [comment]
@abindadna  sir what did you do it fix this URL?

**Comment by Wajidmlk** [comment]
@abindadna  sir what did you do to fix this URL?
