### ISSUE TITLE
How to load url dynamically in vue?

### ISSUE THREAD

**Issue by dipakdas99** [avipunes/file-viewer#4]
Hi @avipunes, In my application, I wanted to load `file-viewer` URL dynamically. Below is my code:

```
<file-viewer id="file-viewer" :filename="fileName" :url="src"
          style="overflow: auto; height: 600px;width: 750px; position: absolute;"></file-viewer>
```

This code is not working for a dynamic URL, like if I have 10 files in my directory and I wanted to load file one by one by clicking on the file. My code is generating a dynamic URL for each file, but unable to load.
Thanks!!

**Comment by avipunes** [comment]
@dipakdas99 my latest commit (https://github.com/avipunes/file-viewer/commit/435cea3051c3c25cb02255f13be6448def547273) should fix that. Please retry.
