### ISSUE TITLE
Office files cannot be displayed

### ISSUE THREAD

**Issue by abindadna** [avipunes/file-viewer#6]
Hi, Does this library have a problem with Digital Ocean servers? Because my Office file is on the DO server it can't be displayed with the message "An error occurred
We're sorry, but for some reason we can't open this for you. "

However, only Office files cannot appear.

Is there a solution for that?

**Comment by avipunes** [comment]
@abindadna can you share an example?

**Comment by robertnicjoo** [comment]
@avipunes  your own sample is a sample of failing display https://codesandbox.io/s/tender-platform-rlxs1?file=/src/index.js

![screenshot-codesandbox io-2020 12 12-14_01_25](https://user-images.githubusercontent.com/8672823/101977763-93526e00-3c82-11eb-9656-5c870e8cecff.jpg)

**Comment by avipunes** [comment]
> @avipunes your own sample is a sample of failing display https://codesandbox.io/s/tender-platform-rlxs1?file=/src/index.js
> 
> ![screenshot-codesandbox io-2020 12 12-14_01_25](https://user-images.githubusercontent.com/8672823/101977763-93526e00-3c82-11eb-9656-5c870e8cecff.jpg)

this URL is not working http://reference1.mapinfo.com/software/anysite/english_AU/tutorials/Sample-Sales-Data.xlsx

**Comment by robertnicjoo** [comment]
@avipunes you're right, I've tested it with this link `https://filebin.net/9iujdtq316oi5o5o/Indonesia_Raya.docx?t=az80srol`  and it worked.

Do you have any vuejs demo of this package? cause your [vue example](https://github.com/avipunes/file-viewer#examples) is linked to react example and I couldn't make it work on my vue app.

**Comment by robertnicjoo** [comment]
@avipunes  Another thing:

This works

```html
<file-viewer
        filename="Sample-Sales-Data.xlsx"
        url="https://filebin.net/9iujdtq316oi5o5o/Indonesia_Raya.docx?t=az80srol"
/>
```

And this doesn't

```html
<file-viewer
        filename="Indonesia_Raya.docx"
        url="https://filebin.net/9iujdtq316oi5o5o/Indonesia_Raya.docx?t=az80srol"
/>
```
